import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const entries = [
  ['curry', 'assets/pets/curry/spritesheet.webp'],
  ['king23', 'assets/pets/king-23/spritesheet.webp'],
]

const encoded = {}
for (const [id, relativePath] of entries) {
  const bytes = await readFile(resolve(root, relativePath))
  encoded[id] = `data:image/webp;base64,${bytes.toString('base64')}`
}

const source = [
  '/** Generated by scripts/embed-assets.mjs. Do not edit by hand. */',
  `export const PET_ASSETS: Readonly<Record<'curry' | 'king23', string>> = ${JSON.stringify(encoded)}`,
  '',
].join('\n')
await writeFile(resolve(root, 'src/client/assets.generated.ts'), source, 'utf8')
